# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41uthentication.proto\x12\x0e\x41uthentication\"Z\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x14\n\x0c\x65nc_password\x18\x02 \x01(\t\x12\x10\n\x08task_num\x18\x03 \x01(\x03\x12\x13\n\x0bstream_name\x18\x04 \x01(\t\"\xb0\x01\n\nLoginReply\x12\x45\n\x11\x63onnection_status\x18\x01 \x01(\x0e\x32*.Authentication.LoginReply.LoginErrorsEnum\"[\n\x0fLoginErrorsEnum\x12\x06\n\x02OK\x10\x00\x12\x19\n\x15\x42\x41\x44_LOGIN_OR_PASSWORD\x10\x01\x12\x10\n\x0c\x42\x41\x44_TASK_NUM\x10\x02\x12\x13\n\x0f\x42\x41\x44_STREAM_NAME\x10\x03\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _globals['_LOGINREQUEST']._serialized_start=40
  _globals['_LOGINREQUEST']._serialized_end=130
  _globals['_LOGINREPLY']._serialized_start=133
  _globals['_LOGINREPLY']._serialized_end=309
  _globals['_LOGINREPLY_LOGINERRORSENUM']._serialized_start=218
  _globals['_LOGINREPLY_LOGINERRORSENUM']._serialized_end=309
# @@protoc_insertion_point(module_scope)
