# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hft1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhft1.proto\x12\x05HFT_1\"\xd8\x01\n\x05\x45vent\x12\x1d\n\x15server_timestamp_usec\x18\x01 \x01(\x03\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12)\n\rbid_ask_event\x18\x03 \x01(\x0b\x32\x12.HFT_1.BidAskEvent\x12\x33\n\x12order_filled_event\x18\x04 \x01(\x0b\x32\x17.HFT_1.OrderFilledEvent\x12/\n\x10stream_end_event\x18\x05 \x01(\x0b\x32\x15.HFT_1.StreamEndEvent\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"_\n\x0b\x42idAskEvent\x12\x12\n\nbid0_price\x18\x01 \x02(\x05\x12\x13\n\x0b\x62id0_volume\x18\x02 \x02(\x05\x12\x12\n\nask0_price\x18\x03 \x02(\x05\x12\x13\n\x0b\x61sk0_volume\x18\x04 \x02(\x05\"b\n\x10OrderFilledEvent\x12\x1d\n\x04side\x18\x01 \x02(\x0e\x32\x0f.HFT_1.SideEnum\x12\x10\n\x08quantity\x18\x02 \x02(\x05\x12\r\n\x05price\x18\x03 \x02(\x05\x12\x0e\n\x06\x66orced\x18\x04 \x02(\x08\"p\n\x0eStreamEndEvent\x12\x0b\n\x03pnl\x18\x01 \x02(\x05\x12\x14\n\x0ctotal_trades\x18\x02 \x02(\x05\x12\x15\n\rmanual_trades\x18\x03 \x02(\x05\x12\x15\n\rforced_trades\x18\x04 \x02(\x05\x12\r\n\x05score\x18\x05 \x01(\x03\"\x18\n\x06Signal\x12\x0e\n\x06signal\x18\x01 \x01(\x05*\x1d\n\x08SideEnum\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hft1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _globals['_SIDEENUM']._serialized_start=577
  _globals['_SIDEENUM']._serialized_end=606
  _globals['_EVENT']._serialized_start=22
  _globals['_EVENT']._serialized_end=238
  _globals['_BIDASKEVENT']._serialized_start=240
  _globals['_BIDASKEVENT']._serialized_end=335
  _globals['_ORDERFILLEDEVENT']._serialized_start=337
  _globals['_ORDERFILLEDEVENT']._serialized_end=435
  _globals['_STREAMENDEVENT']._serialized_start=437
  _globals['_STREAMENDEVENT']._serialized_end=549
  _globals['_SIGNAL']._serialized_start=551
  _globals['_SIGNAL']._serialized_end=575
# @@protoc_insertion_point(module_scope)
